name: Extract Domains # نام گردش کار شما
on:
  push: # راه‌اندازی گردش کار در هر هل
    branches:
      - main # در شاخه اصلی
  schedule:
    - cron: '0 0 * * *'  # اجرای روزانه در 00:00 UTC
jobs:
  extract_domains:
    runs-on: ubuntu-latest # استفاده از یک ماشین لینوکس اوبونتو
    steps:
      - uses: actions/checkout@v4 # واکشی کد مخزن
      - name: Set up Python # نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # یا هر نسخه پایتون مورد نیاز
      - name: Install dependencies # نصب وابستگی ها
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 # نصب کتابخانه های مورد نیاز
      - name: Run the script # اجرای اسکریپت پایتون
        run: python extract_domains.py > results.txt # فرض می کند نام اسکریپت شما extract_domains.py است و خروجی را به results.txt هدایت می کند
      - name: Commit and push results # اضافه کردن برای کامیت و فش خروجی (اختیاری)
        if: success() # فقط در صورت موفقیت اجرای اسکریپت اجرا شود
        run: |
          git config --local user.email "your-email@example.com" # پیکربندی اطلاعات گیت
          git config --local user.name "Your Name"
          git add results.txt # فایل results.txt را اضافه می کند
          git commit -m "Update extracted domains"
          git push
