name: Extract Domains
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC

jobs:
  extract_domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pillow pytesseract

      - name: Run Python script and capture output
        run: python extract_domains.py > output.txt

      - name: Show extracted domains
        run: cat output.txt

      - name: Commit and push results
        if: success()
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add output.txt
            git commit -m "Update extracted domains"
            git push
          else
            echo "No changes to commit"
          fi
