name: Extract Domains
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC

jobs:
  extract_domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and Chrome
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Run Python script and capture output
        run: |
          python extract_domains.py || true

      - name: Show extracted domains
        run: cat output.txt || true

      - name: Commit and push results
        run: |
          git config --local user.email "bot@example.com"
          git config --local user.name "Auto Bot"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add output.txt
            git commit -m "Update extracted domains"
            git push
          else
            echo "No changes to commit"
          fi  # <-- Added missing 'fi' to close the if statement
